server {
  listen 80;
  server_name _;

  root /usr/share/nginx/html;
  index index.html;

  location = / {
    return 302 $scheme://$http_host/artemis-2/;
  }

  location /artemis-2/assets/ {
    alias /usr/share/nginx/html/assets/;
    access_log off;
    expires 1y;
    add_header Cache-Control "public, immutable";
  }

  location /artemis-2/starmaps/ {
    alias /usr/share/nginx/html/starmaps/;
    access_log off;
    expires 1y;
    add_header Cache-Control "public, immutable";
  }

  location = /artemis-2/favicon.svg {
    alias /usr/share/nginx/html/favicon.svg;
  }

  location = /artemis-2/icons.svg {
    alias /usr/share/nginx/html/icons.svg;
  }

  location /artemis-2/ {
    try_files $uri $uri/ /index.html;
  }
}
