import { Stars } from '@react-three/drei';

/**
 * Realistic starfield using @react-three/drei's Stars component.
 * Uses a particle system with ~6000 stars. For a real star catalog,
 * this can be replaced with a custom THREE.Points geometry loaded
 * from /data/stars.json (generated by the Python pipeline).
 */
export default function Starfield() {
  return (
    <Stars
      radius={8_000_000}   // sphere radius in scene units (km)
      depth={50_000}        // depth of the star field
      count={6000}
      factor={4}
      saturation={0.3}
      fade={false}
      speed={0}
    />
  );
}
