import { useMemo } from 'react';
import MarkdownRenderer from './MarkdownRenderer';
import { useMissionStore, type LearnSection } from '../../store/missionStore';
import styles from './LearnDialog.module.css';
import bcrsExplainerImage from '../../../docs/img/BCRS_explainer.jpg';
import gcrsExplainerImage from '../../../docs/img/GCRS_explainer.jpg';

interface LearnDialogProps {
  onClose: () => void;
}

interface LearnIllustration {
  src: string;
  alt: string;
  caption: string;
}

const SECTIONS = [
  {
    id: 'sources',
    label: 'Sources',
    summary: 'Where the app gets vectors, textures, and sky maps.',
    content: `
This section lists the concrete sources behind the app's visible data products.

## 1. Earth, Sun, and Moon positions

The app's \`ephemeris.json\` file is generated by the local SPICE pipeline in \`scripts/fetch_ephemeris.py\`.

- **Sun position**: SPICE \`spkez(SUN, et, "J2000", "NONE", EARTH)\`
- **Moon position**: SPICE \`spkez(MOON, et, "J2000", "NONE", EARTH)\`
- **Earth barycentric position**: SPICE \`spkez(EARTH, et, "J2000", "NONE", SSB)\`

The pipeline downloads and uses these NAIF kernels:

- [DE440s planetary ephemeris](https://naif.jpl.nasa.gov/pub/naif/generic_kernels/spk/planets/de440s.bsp)
- [PCK planetary constants kernel](https://naif.jpl.nasa.gov/pub/naif/generic_kernels/pck/pck00011.tpc)
- [NAIF leap-seconds kernel](https://naif.jpl.nasa.gov/pub/naif/generic_kernels/lsk/naif0012.tls)

In the default GCRS scene, Earth is displayed at the origin by definition. In BCRS mode, Earth uses the stored \`earthPosBCRS\` vector from that same SPICE-generated ephemeris file.

## 2. Earth rotation and Moon orientation

These also come from the SPICE pipeline in \`scripts/fetch_ephemeris.py\`.

- **Earth rotation**: derived from \`pxform("J2000", "IAU_EARTH", et)\`, stored in the app as \`gmstRad\`
- **Moon orientation**: derived from \`pxform("J2000", "IAU_MOON", et)\`, stored as the Moon orientation samples used by the frontend

## 3. Artemis II trajectory

The spacecraft trajectory in \`trajectory.json\` comes from the [JPL Horizons REST API](https://ssd.jpl.nasa.gov/api/horizons.api).

The query used by the pipeline in \`scripts/fetch_trajectory.py\` is geocentric and inertial:

- target: \`COMMAND = -1024\`
- center: \`500@399\` (Earth geocenter)
- frame: \`REF_SYSTEM = J2000\`
- plane: \`REF_PLANE = FRAME\`
- units: \`KM-S\`

That makes the trajectory a geocentric inertial state history in the same practical J2000 / ICRF-aligned frame used elsewhere in the app.

## 4. Sky maps

The star background comes from [NASA SVS Deep Star Maps 2020](https://svs.gsfc.nasa.gov/4851).

The local download script \`scripts/download_starmaps.py\` fetches these EXR files into \`public/starmaps/\`:

- \`starmap_2020_4k.exr\`
- \`starmap_2020_8k.exr\`
- \`starmap_2020_16k.exr\`

In the frontend, the texture is mirrored horizontally so right ascension increases in the correct direction for the app's axis convention.

## 5. Earth textures

The Earth texture stack is prepared by \`scripts/download_textures.py\`.

Source family:

- [Solar System Scope textures](https://www.solarsystemscope.com/textures/)  
  licensed as **CC BY 4.0**, based on NASA Blue Marble / Black Marble

Frontend Earth texture files:

- \`earth_day_8k.jpg\`
- \`earth_night_8k.jpg\`
- \`earth_clouds_8k.jpg\`
- \`earth_normal_8k.jpg\`
- \`earth_specular_8k.jpg\`

These files are downloaded from Solar System Scope source assets and converted into the canonical filenames expected by the frontend.

## 6. Moon textures

The Moon texture stack is also prepared by \`scripts/download_textures.py\`.

Sources:

- [NASA SVS CGI Moon Kit](https://svs.gsfc.nasa.gov/4720)
- 2025 LROC color map used for the Moon albedo texture
- LOLA displacement data used to generate the Moon normal map locally

Frontend Moon texture files:

- \`moon_8k.jpg\`
- \`moon_normal_8k.jpg\`

The Moon normal map is not downloaded as a finished image. It is generated locally from the LOLA displacement TIFF in the texture-preparation script.
`,
  },
  {
    id: 'world',
    label: '3D World',
    summary: 'Render axes, handedness, and camera conventions.',
    content: `
The app render world is **right-handed**. It is used as a direct mapping of the selected scene frame into Three.js world space.

Core render rules:

- $+X$ is red
- $+Y$ is green
- $+Z$ is blue
- $+Z$ is the app-wide up axis

No extra handedness change or axis remapping is inserted between the scene model and the rendered scene. If the selected frame places something at positive $Z$, it appears on the positive blue axis in the scene and in the world indicator.

Three.js and WebGL do not impose a scientific "screen up" convention. In this app, camera views are initialized with:

$$
\\mathbf{up}_{camera} = (0,0,1)
$$

so the blue axis starts out visually up.

The camera local frame is also right-handed:

- local $-Z$ is the optical axis
- local $+X$ is camera-right
- local $+Y$ is camera-up

Practical consequence:

- camera **position** is a Cartesian vector in kilometers
- camera **forward** and **up** are direction vectors
- the camera panel converts those direction vectors into RA/Dec for display

The world indicator is locked to the inertial frame. As the camera moves, the indicator shows how the camera is oriented relative to the fixed world axes.
`,
  },
  {
    id: 'frames',
    label: 'Frames',
    summary: 'GCRS-like motion, SPICE rotation, and body-fixed orientation.',
    illustrations: [
      {
        src: gcrsExplainerImage,
        alt: 'Concept diagram of the geocentric frame used by the app, with Earth at the center and the main inertial axes shown.',
        caption: 'Concept sketch of the app’s geocentric view: Earth at the origin, with the practical J2000 / ICRF-aligned inertial axes used by the scene.',
      },
      {
        src: bcrsExplainerImage,
        alt: 'Concept diagram of the barycentric frame used by the app, with the Solar System barycenter at the origin and the main inertial axes shown.',
        caption: 'Concept sketch of the barycentric view: the Solar System barycenter at the origin, with the same practical inertial axis orientation carried into BCRS mode.',
      },
    ] satisfies LearnIllustration[],
    content: `
The viewer uses more than one frame because translation, body rotation, and texture registration are different problems. Inertial positions answer "where is the body in space?"; body-fixed frames answer "which way is the surface facing?"

## 1. ICRS, BCRS, and GCRS

At the standards level:

- **ICRS** defines the orientation of the celestial axes
- **BCRS** is the barycentric celestial reference system
- **GCRS** is the geocentric celestial reference system

These are not just translated Cartesian grids. In the formal IAU/IERS framework they are reference systems with defined origins, coordinate times, and transformations.

For this app, the practical distinction is:

- **GCRS mode**: Earth-centered inertial coordinates
- **BCRS mode**: Solar-System-barycentric inertial coordinates
- both use the same practical inertial axis orientation

So the main visible difference between the two modes is the **origin**.

## 2. Practical inertial axes in this app

In SPICE and many mission tools, the working inertial frame is labeled **J2000**. Modern products such as DE4xx ephemerides are effectively aligned with the **ICRF**, even though the historical frame label often stays \`J2000\`.

For visualization and mission geometry work, the following names are commonly treated as the same practical axis set to very high precision:

- ICRF
- ICRS realization
- J2000
- EME2000

This app follows that practical convention for imported ephemerides and for the night-sky background.

## 3. Earth-fixed and Moon-fixed frames

Earth texture registration and Moon texture registration do **not** belong to the inertial frame. They belong to rotating body-fixed frames.

For Earth, the app uses a rotation about inertial $+Z$ based on the stored \`gmstRad\` value, so Earth-fixed longitude stays tied to Earth rotation.

For the Moon, the app uses the SPICE body-fixed orientation:

- \`pxform("J2000", "IAU_MOON", et)\` in the data pipeline
- rendered in the frontend as a Moon body-frame quaternion

This is why a correct scene needs both:

- **translation** from an inertial ephemeris
- **rotation** from a body-fixed orientation model

## 4. Frames used directly by this app

The app uses these frame classes directly:

- **GCRS-like geocentric inertial render frame**
- **BCRS-like barycentric render frame**
- **Earth body-fixed orientation**
- **Moon body-fixed orientation**
- **mean ecliptic-of-J2000 helper plane**

For the default geocentric scene:

$$
\\mathbf{r}_{Earth} = (0,0,0)
$$

by definition.

In BCRS mode, the app uses \`earthPosBCRS\` from \`ephemeris.json\` for Earth, and places the Moon and spacecraft by adding their geocentric vectors to Earth. That keeps the displayed bodies in one barycentric scene while preserving the same practical inertial axis orientation.

## 5. Other frame families you may see elsewhere

Mission software also uses local orbital frames such as LVLH or RTN, and Earth-orientation frames such as TEME or true-of-date systems. Those are important in guidance, TLE/SGP4, and precise Earth-orientation workflows, but they are not scene frames used directly by this viewer.

## 6. Render-space convention

After the scientific vectors are defined, the app maps them into a render world that stays:

- right-handed
- $+X$ red
- $+Y$ green
- $+Z$ blue
- $+Z$ up

The camera local frame also stays right-handed:

- local $-Z$ is the viewing direction
- local $+X$ is camera-right
- local $+Y$ is camera-up

The point of this convention is simple: preserve the frame geometry on screen without hidden axis swaps.

## Primary references

- [IAU resolutions overview for reference systems](https://iau-a3.gitlab.io/res.html)
- [NAIF SPICE Frames Required Reading](https://naif.jpl.nasa.gov/pub/naif/toolkit_docs/FORTRAN/req/frames.html)
- [NAIF notes on inertial and body-fixed frames](https://naif.jpl.nasa.gov/naif/WGC_about_the_data_r2.html)
- [IERS Conventions](https://www.iers.org/IERS/EN/DataProducts/Conventions/conventions)
- [IERS overview of ITRF / ITRS realizations](https://www.iers.org/IERS/EN/DataProducts/ITRF/itrf)
`,
  },
  {
    id: 'data',
    label: 'Data',
    summary: 'Horizons trajectory, SPICE Moon state, and the sky map.',
    content: `
This app combines several data products, and each one needs a clear coordinate and time contract.

## 1. Translational ephemerides

The Sun and Moon scene positions come from inertial ephemeris data derived from the project's DE440 / SPICE pipeline. In the default GCRS view, Earth stays at \`(0,0,0)\` by definition. In the BCRS view, Earth uses the stored \`earthPosBCRS\` values from \`ephemeris.json\`.

For each translational dataset, the key questions are:

- **origin**
- **axis orientation**
- **units**
- **time tag**

Those four items tell you what the vector means and how it can be combined with the rest of the scene.

## 2. Spacecraft trajectory

The Artemis trajectory is loaded from **JPL Horizons vector tables**. The authoritative target is \`-1024\`, and Horizons also resolves \`Artemis II\` to the same spacecraft identity. In the geocentric scene, the required contract is:

- origin: Earth center
- axes: practical \`GCRS\`-like / Earth-centered \`J2000\` / \`ICRF\`-aligned inertial axes
- distance units: kilometers
- velocity units: kilometers per second
- \`COMMAND = -1024\`
- \`CENTER = 500@399\`
- \`REF_SYSTEM = J2000\`
- vector reference plane: \`REF_PLANE=FRAME\`
- \`OUT_UNITS = KM-S\`

That query contract keeps the trajectory in the same Earth-centered inertial frame family as the rest of the app.

## 3. Rotational and cartographic data

Earth and Moon textures are not inertial datasets. They belong to rotating body-fixed frames.

That means the app has to know:

- where the north pole is
- where longitude $0^\\circ$ is
- how the prime meridian rotates with time
- how the image is registered to that longitude/latitude grid

For the Moon, the body-fixed orientation is derived from SPICE \`pxform("J2000", "IAU_MOON", et)\`.

A coherent scene therefore combines:

- inertial translation
- body-fixed rotation
- texture registration that matches the body-fixed frame

## 4. Celestial background

The night-sky map comes from **NASA SVS Deep Star Maps 2020** in equirectangular form. Its role is to encode directions on the celestial sphere using:

- right ascension
- declination
- practical ICRF / J2000 orientation

In the frontend, the texture is mirrored horizontally before it is applied to the inside of the sky sphere, so increasing right ascension matches the app's right-handed axis convention.

## 5. Time systems

The UI shows mission time mainly as **UTC**, but the underlying astronomical products use their own declared time scales.

The important distinction in this app is:

- **UTC**: user-facing display time
- **trajectory / ephemeris time tags**: the declared epochs attached to imported vector products
- **Earth rotation**: precomputed \`gmstRad\` samples stored in \`ephemeris.json\`

The frontend does not derive UT1 or GMST live. It reads the stored ephemeris arrays and interpolates them for the current epoch.

## 6. Practical source summary

Useful short descriptions for the current app:

- **Sun position**: inertial vector from the ephemeris pipeline in the app's practical J2000 / ICRF-aligned frame
- **Earth position**: origin in GCRS; \`earthPosBCRS\` in BCRS mode
- **Moon translational state**: local SPICE \`spkez(MOON, et, "J2000", "NONE", EARTH)\` result in Earth-centered inertial coordinates
- **Spacecraft trajectory**: Horizons vectors for target \`-1024\` in Earth-centered inertial coordinates with the declared frame-plane settings
- **Earth rotation**: interpolated \`gmstRad\` values from \`ephemeris.json\`
- **Moon orientation**: body-fixed Moon orientation from the SPICE pipeline
- **Star map**: celestial sphere texture registered to right ascension and declination in the same inertial orientation
`,
  },
  {
    id: 'camera',
    label: 'Camera',
    summary: 'Locking, pointing, and telemetry readout.',
    content: `
The camera can lock to **Earth**, **Moon**, **spacecraft**, or **overview**.

Locking means:

- the orbit center follows the selected object
- the user can still orbit, pan, and change distance

The Camera panel reports:

- Cartesian position in kilometers
- forward direction as RA/Dec, with the underlying vector available in the tooltip
- up direction as RA/Dec, with the underlying vector available in the tooltip

Pointing input accepts decimal degrees or degree-minute forms such as 120 30 or 120:30.

Accepted examples:

- 120.5
- 120 30
- 120:30
- 120d30m

The internal conversion is:

$$
\\hat{u} =
\\begin{bmatrix}
\\cos \\delta \\cos \\alpha \\\\
\\cos \\delta \\sin \\alpha \\\\
\\sin \\delta
\\end{bmatrix}
$$

where $\\alpha$ is right ascension and $\\delta$ is declination.

Operationally:

- RA wraps through $360^\\circ$
- Dec is constrained to $[-90^\\circ, +90^\\circ]$
- the entered direction is normalized before it is used

Useful reference cases:

- $RA = 90^\\circ$, $Dec = 0^\\circ$ points along $+Y$
- $RA = 0^\\circ$, $Dec = 90^\\circ$ points along $+Z$

So the camera control is asking for a **direction on the celestial sphere**, not a target distance or a target position. The current lock center or orbit target then determines what the camera is looking at along that direction.
`,
  },
  {
    id: 'planning',
    label: 'Planning',
    summary: 'How this relates to mission analysis products.',
    content: `
This viewer combines mission-state products with rotation models and texture registration.

JPL Horizons and SPICE provide translational states with declared:

- origin
- axes
- units
- time scale

For this project, the verified source split is:

- spacecraft trajectory: JPL Horizons target \`-1024\`
- Moon translational state: local SPICE \`spkez(MOON, et, "J2000", "NONE", EARTH)\`
- Moon orientation: local SPICE \`pxform("J2000", "IAU_MOON", et)\`

There are no analytical ephemeris fallback paths and no simulated trajectory fallback paths in the authoritative pipeline.

To keep the rendered scene coherent, the app has to preserve several links between the source data and the display:

1. the state vector must come from the declared source
2. the source frame must be identified correctly
3. time tags must be interpreted correctly
4. body-fixed texture registration must match the rotational model
5. debugging aids must show the same frame geometry as the scene

That is why the app exposes:

- world axes
- ecliptic orientation
- object-local axes
- camera telemetry

Those readouts let you compare the rendered scene with the frame and orientation conventions behind it.
`,
  },
] as const;

export default function LearnDialog({ onClose }: LearnDialogProps) {
  const activeTab = useMissionStore((s) => s.learnSection);
  const setLearnSection = useMissionStore((s) => s.setLearnSection);
  const activeSection = useMemo(
    () => SECTIONS.find((section) => section.id === activeTab) ?? SECTIONS[0],
    [activeTab],
  );

  return (
    <div className={styles.overlay} onClick={onClose}>
      <div
        className={`${styles.dialog} hud-panel`}
        onClick={(e) => e.stopPropagation()}
        role="dialog"
        aria-modal="true"
        aria-label="Learn"
      >
        <div className={styles.header}>
          <div className={styles.headerText}>
            <div className={styles.title}>Learn</div>
            <div className={styles.text}>Frames, handedness, camera axes, and where the astronomy data comes from.</div>
          </div>
          <button type="button" className={styles.close} onClick={onClose} aria-label="Close Learn dialog">
            <svg viewBox="0 0 24 24" className={styles.closeIcon} aria-hidden="true">
              <path d="M7 7l10 10M17 7L7 17" />
            </svg>
          </button>
        </div>

        <div className={styles.body}>
          <div className={styles.tabs} role="tablist" aria-label="Learn sections">
            {SECTIONS.map((section) => {
              const selected = section.id === activeSection.id;
              return (
                <button
                  key={section.id}
                  type="button"
                  role="tab"
                  aria-selected={selected}
                  className={`${styles.tab} ${selected ? styles.tabActive : ''}`}
                  onClick={() => setLearnSection(section.id as LearnSection)}
                >
                  <span className={styles.tabLabel}>{section.label}</span>
                  <span className={styles.tabSummary}>{section.summary}</span>
                </button>
              );
            })}
          </div>

          <div className={styles.panel}>
            <div className={styles.scrollArea}>
              <div className={styles.contentHeader}>
                <div className={styles.contentTitle}>{activeSection.label}</div>
                <div className={styles.contentSummary}>{activeSection.summary}</div>
              </div>
              {('illustrations' in activeSection) && activeSection.illustrations && (
                <div className={styles.illustrations}>
                  {activeSection.illustrations.map((illustration) => (
                    <figure key={illustration.src} className={styles.figure}>
                      <img
                        src={illustration.src}
                        alt={illustration.alt}
                        className={styles.figureImage}
                      />
                      <figcaption className={styles.figureCaption}>{illustration.caption}</figcaption>
                    </figure>
                  ))}
                </div>
              )}
              <MarkdownRenderer content={activeSection.content} className={styles.markdown} />
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
